### ISSUE TITLE
org.jsoup.UncheckedIOException: java.net.SocketTimeoutException Read timeout

### ISSUE THREAD

**Issue by evi1a** [skrapeit/skrape.it#1]
Once in a while I get this exception and I don't know how to prevent it from happening:
`org.jsoup.UncheckedIOException: java.net.SocketTimeoutException: Read timeout`

```
Caused by: java.net.SocketTimeoutException: Read timeout
	at org.jsoup.internal.ConstrainableInputStream.read(ConstrainableInputStream.java:58)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.jsoup.internal.ConstrainableInputStream.readToByteBuffer(ConstrainableInputStream.java:87)
	at org.jsoup.helper.DataUtil.readToByteBuffer(DataUtil.java:175)
	at org.jsoup.helper.HttpConnection$Response.prepareByteData(HttpConnection.java:863)
	... 9 more
```

**Comment by christian-draeger** [comment]
Hey, thx for reporting. Could you provide an example on how you are doing the call?
Ihow the url is build would be point of interest in that case, but a complete code example would be nice as well

**Comment by evi1a** [comment]
```Kotlin
fun byTeam(teamId: Int): Fixtures {
        try {
            return skrape {
                url = "https://www.transfermarkt.co.uk/team/spielplandatum/verein/$teamId"
                expect {
                    statusCode toBe 200
                }
                extract {
                    val team = Team(
                        id = extractIdFromImgUrl(element("#verein_head .dataBild img").attr("src"))!!,
                        name = element("#verein_head .dataName").text(),
                        logo = element("#verein_head .dataBild img").attr("src")
                    )
                    Fixtures(
                        team = team,
                        matches = extractMatchesHelper(element(".kartei-button-bar").nextElementSibling().select(".responsive-table tbody tr"), team)
                    )
                }
            }
        } catch (e: AssertionError) {
            throw IllegalArgumentException("There is no team with the given id")
        }
    }
```

The thing is, it works perfect most of the times. It's just sometimes that I get the exception...

**Comment by christian-draeger** [comment]
This exception usually happens if the requested server is not answering fast enough, this can have multiple reasons like network issues (skrapeits default timeout is 5000 milliseconds).
See: https://docs.skrape.it/docs/dsl/how-to-make-a-http-request

You could try to bump the timeout for now like so:
```
skrape {
    url = "..." 
    timeout = 10000
   ... 
} 
```
But anyway i will soonish investigate if this can be done more stable or add least throwing a more meaningful exception

**Comment by evi1a** [comment]
Danke, scheint jetzt in Ordnung zu sein. Habe dennoch ne Frage und zwar wie sieht's aus wenn ich Anfragen verschachteln muss. Wie mache ich das am besten? Gibt es da vielleicht eine Möglichkeit, dass die Anfrage erst beim Zugriff auf den jeweiligen Datensatz erfolgt? Danke im voraus

**Comment by christian-draeger** [comment]
Also es ist jetzt schon so das der http call erst ausgeführt wird wenn das erstemal `expect` oder `extract` innerhalb des `skrape` scopes aufgerufen wird.
