### ISSUE TITLE
[FEATURE] make it async with coroutines

### ISSUE THREAD

**Issue by christian-draeger** [skrapeit/skrape.it#104]
fun fetch(request: T) could be suspend, but then we would force the user to execute the top-level skrape {} DSL from within a coroutine context, what we don't want to.
but we could provide a fetchAsync function to the DSL and make everything work with coroutines. the existing fetch function could just run it blocking.

**Comment by Caps-Looking** [comment]
Isn't the AsyncFetcher the implementation for that?

**Comment by christian-draeger** [comment]
This is correct. I am currently (really today 😄) in the middle of a refactoring regarding that topic to make it a bit more convenient to use and first and foremost to reduce/remove internal code duplication. Thereby things could slightly change and this issue will be closed if refactoring is done
