### ISSUE TITLE
[BUG] Code similar to exemple produce error

### ISSUE THREAD

**Issue by Driky** [skrapeit/skrape.it#106]
**Describe the bug**
I'm using the following 
```kotlin
it.link = span {
                    withClass = "lchx"
                    findFirst {
                        a { findFirst { attribute("href") }}
                    }
                }
```
and I get `'fun <T> Doc.a(cssSelector: String = ..., init: CssSelector.() -> String): String' can't be called in this context by implicit receiver. Use the explicit one if necessary`

**Expected behavior**
No error and `it.link` is set to the value of the href attribute.

**Full Code**
```Kotlin
import it.skrape.core.fetcher.Method
import it.skrape.core.fetcher.Mode
import it.skrape.core.htmlDocument
import it.skrape.extractIt
import it.skrape.selects.html5.span
import it.skrape.selects.html5.a
import it.skrape.skrape
 
    data class MyExtractedChapter(
        var text: String = "",
        var link: String = ""
    )
fun main() {
    val extracted = skrape {
        url = "https://someurl.com"
        mode = Mode.DOM // optional -> defaults to SOURCE (plain http request) - DOM will also render JS
        method = Method.GET // optional -> defaults to GET
        timeout = 5000 // optional -> defaults to 5000ms
        followRedirects = true // optional -> defaults to true
        userAgent = "some custom user agent" // optional -> defaults to "Mozilla/5.0 skrape.it"
        cookies = mapOf("some-cookie-name" to "some-value") // optional
        headers = mapOf("some-custom-header" to "some-value") // optional

        extractIt<MyExtractedChapter> { it ->
            htmlDocument {

                it.text = span {
                    withClass = "lchx"
                    findFirst {
                        text
                    }
                }

                it.link = span {
                    withClass = "lchx"
                    findFirst {
                        a { findFirst { attribute("href") } }
                    }
                }
            }
        }
    }
}
```
Note:
I based myself on this part of the doc https://github.com/skrapeit/skrapeit-docs/blob/1.0.0-alpha6/dsl/extracting-data-from-websites.md And it appears the exemple does not compile.

**Comment by christian-draeger** [comment]
hmm could you please try to import the lib as follows (just to check if the docs are not lying on the version)

```kotlin
repositories {
    jcenter()
    maven {
        url = uri("https://jitpack.io")
    }
}

implementation("com.github.skrapeit:skrape.it:ecbec25908")
```

**Comment by Driky** [comment]
Indeed with experimental features activated my code works !

**Comment by christian-draeger** [comment]
great,  i will update the docs soonish

**Comment by Driky** [comment]
For curriosity's sake is there a way without experiemental features to nest element selectors ?

**Comment by christian-draeger** [comment]
no unfortunately not.
but api wise the usage und functionality (also element nesting) will not change in 1.0.0-final release. only thing that will be different is how to define requests (but also in the master and documented in the master README file).
only reason that 1.0.0-final isnt released is an ongoing project structure refactoring (multi module project).
