### ISSUE TITLE
[BUG] Request headers not being added

### ISSUE THREAD

**Issue by coder82** [skrapeit/skrape.it#107]
When using the HttpFetcher, the custom headers are not added the the request, see picture, the statement pointed by the arrow does nothing.

![image](https://user-images.githubusercontent.com/26207876/94243484-c0ab3d80-ff17-11ea-89aa-a228f574ce87.png)

**Comment by coder82** [comment]
I suggest to do this:

```
request.headers.forEach { k, v ->
   k to v
}
```

**Comment by christian-draeger** [comment]
You are right. I just checked the tests and if custom headers will be send is even not tested. 😬 Would you mind to send a pull request?
