### ISSUE TITLE
[IMPROVEMENT] migrate the project from maven to gradle

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#11]
the build tool of our choice should be gradle, therefore we want to migrate mavens pom.xml to a **gradle.build.kts** using the gradle Kotlin DSL!

ACs:
* migrated build tooling from maven to gradle with Kotlin dsl
* remove maven wrapper 
* add gradle wrapper
* adjust travis build file

**Comment by fejd** [comment]
@skrapeit I can pick up this one and #16.

**Comment by skrapeit** [comment]
nice :) thx a lot in advance

**Comment by fejd** [comment]
Thanks! I'm halfway there (I think) - the build works and the tests run. Left to do:
* Some tests are failing, investigate why
* Get all the POM information into the maven publishing block
* Adjust Travis build file

**Comment by skrapeit** [comment]
awesome :)

**Comment by fejd** [comment]
Fixed in https://github.com/skrapeit/skrape.it/pull/62
