### ISSUE TITLE
[IMPROVEMENT] make ktor extension a submodule of this repo

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#114]
since we have a gradle multi module build it would make sense to make the [ktor-extension](https://github.com/skrapeit/skrapeit-ktor-extension) be part of this repo. this will kale release process more easy and always tested for compatibility. we will release the extension whenever a new core version has been released. all will always have the same version to indicate they have been tested together.

ktor-exension repo can be archived after successful migration

**Comment by faogustavo** [comment]
Can I take this one?

**Comment by christian-draeger** [comment]
Sure :)

**Comment by faogustavo** [comment]
@christian-draeger the `Parser` class is only internal now. Is there a public version of it? The ktor version needs it 😬 

```kotlin
fun TestApplicationResponse.expectHtml(init: Doc.() -> Unit): Doc {
    val response = this.content ?: throw IllegalArgumentException("can not parse document of content null")
    return Parser(response).parse().also(init)
}
```

**Comment by skrapeit** [comment]
> Edit: Nevermind, I found it 🤦‍♂️

glad to hear :D

Parser usage has changed a bit since but should be possible

**Comment by faogustavo** [comment]
@christian-draeger just opened a PR with the library import.
I had to rewrite parts of the code, but I believe that it kept the same purpose.

**Comment by christian-draeger** [comment]
looks good to me thx 👍
