### ISSUE TITLE
Add android example project

### ISSUE THREAD

**Issue by christian-draeger** [skrapeit/skrape.it#121]
We have an examples module. Here we want to showcase possible usages of skrapeit and have a living documentation by example.
Therefore we would like to have a small android example project as subfolder of the examples module.
It could be something like skrape some data from somewhere and just display it.

This would be nice starting point for the Android devs to use skrapeit.

**Comment by faogustavo** [comment]
@christian-draeger now we have the android sample :)
The PR linking to the repo is already open. After merge we can close this one.

Here is a print of the sample app:

![image](https://user-images.githubusercontent.com/7588480/95457806-c9543880-0947-11eb-9dff-9812d88b0df6.png)

**Comment by christian-draeger** [comment]
Thx u are awesome :) really big thanks
