### ISSUE TITLE
[IMPROVEMENT] unify maven central release process 

### ISSUE THREAD

**Issue by christian-draeger** [skrapeit/skrape.it#123]
Since we have submodules like core, mockmvc, ktor, and more in the future it would be nice to have a unified way of releasing these artifacts to mVen central.
Currently we are using a gradle plugin to this with the core module.
But all modules should support the release process. If that would be possible via github actions somehow it would be awesome.

**Comment by christian-draeger** [comment]
1.0.0 release waits for #127

**Comment by christian-draeger** [comment]
multi module spilt (#69) done ✅

**Comment by christian-draeger** [comment]
after multi module split we have following modules that should be released separat:
* it.skrape:skrapeit-assertions
* it.skrape:skrapeit-basis-fetcher 
* it.skrape:skrapeit-http-fetcher
* it.skrape:skrapeit-browser-fetcher
* it.skrape:skrapeit-html-parser
* it.skrape:skrapeit-ktor-extension
* it.skrape:skrapeit-mock-mvc-extension

and an aggregator release that is including all the modules and is build from preject root--> it.skrape:skrapeit

**Comment by ruffCode** [comment]
I have a fix for this I think.

The issue with the fetchers modules is in how they are referenced throughout the project. Gradle is treating the root fetchers folder as a module.

In settings.gradle.kts, include the modules this way, then in all the imports change ":fetchers:submodule" to ":submodule" 
```include(":basis-fetcher")
include(":http-fetcher")
include(":ktor-fetcher")
include(":browser-fetcher")
project(":basis-fetcher").projectDir = file("fetcher/basis-fetcher")
project(":http-fetcher").projectDir = file("fetcher/http-fetcher")
project(":ktor-fetcher").projectDir = file("fetcher/ktor-fetcher")
project(":browser-fetcher").projectDir = file("fetcher/browser-fetcher")
```

Place a "gradle.properties" in every module you want to publish with 
```
POM_ARTIFACT_ID=
POM_NAME=
POM_DESCRIPTION=
VERSION_NAME=
```

In the root build.gradle, we want to make sure that the publishing plugin is only being applied to the artifacts you want to publish.
So we can declare, for instance,  `val excludeFromPublishing = listOf( "dsl", "examples", "test-utils", "scraping")` 

Then, remove `apply(plugin = "com.vanniktech.maven.publish")` from the allprojects block and in the subprojects block 
```
subprojects {
    if (this.name !in excludeFromPublishing) {
        apply(plugin = "com.vanniktech.maven.publish")
    }
//.....
}
```

I tested this by publishing to mavenLocal and it seemed to work.

**Comment by christian-draeger** [comment]
Ok will try as soon as I am back 2 keyboard :) big thx for figuring out 🙂
