### ISSUE TITLE
[IMPROVEMENT] use qodana as linter

### ISSUE THREAD

**Issue by christian-draeger** [skrapeit/skrape.it#131]
Qodana comprises two main parts: a nicely packaged GUI-less IntelliJ IDEA engine tailored for use in a CI pipeline as a typical “linter” tool, and an interactive web-based reporting UI.

https://blog.jetbrains.com/idea/2021/02/early-access-program-for-qodana-a-new-product-that-brings-the-smarts-of-jetbrains-ides-into-your-ci-pipeline/

**Comment by msotho** [comment]
Hi. I want to try implement this. 

Is the idea to set up for the GitHub Actions and generate the html report for the results?

Thanks.

**Comment by christian-draeger** [comment]
Yes exactly. The idea is to have a static code analysis as a quality gate being part of the ci pipeline :)

**Comment by msotho** [comment]
Understood. I've done something similar in our company repos.

I plan to implement it and raise a PR over the next weekend 😃

**Comment by christian-draeger** [comment]
Nice :) thank you very much
