### ISSUE TITLE
[IMPROVEMENT] replace http client (HttpFetcher)

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#14]
we want to use [KoHttp](https://github.com/rybalkinsd/kohttp) as our http client of choice because it has a nice Kotlin DSL and native support for non-blocking requests.

**Comment by djcass44** [comment]
Can you clarify a bit, do you want to replace the Browser/HttpFetcher or add an additional one?

**Comment by djcass44** [comment]
I just opened #64, let me know if it's what you're looking for
