### ISSUE TITLE
[IMPROVEMENT] migrate CI build from travis to GitHub action

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#15]

**Comment by idodin** [comment]
Hi, could I get some more information about the rationale behind this issue? i.e. why are you lookign to migrate to GHA - is Travis introducing any kind of delays?

**Comment by skrapeit** [comment]
not really. but travis is currently making trouble when trying to install jdk8 on ubuntu > trusty
see: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/12

and I think it would be nice to have everything in one place. and after a playing around with GHA in another project it looks very promising
