### ISSUE TITLE
[IMPROVEMENT] make static code analysis work with gradle

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#16]
we are currently using **detekt** as static source code analysis tool. 
at the moment this is configured by using a maven plugin. make it work with gradle (it exists a plugin as well)

!! has to be done after #11

**Comment by DeKaN** [comment]
I would like to do it

**Comment by skrapeit** [comment]
nice I will asign you and thx in advance.
FYI: we are already having an [detekt.yml](https://github.com/skrapeit/skrape.it/blob/master/src/test/resources/detekt.yml) in the project that was used before we migrated from maven to gradle
but I would be open to also use ktlint instead of detekt. feel free to choose one :)
