### ISSUE TITLE
[BUG] Android support not working 

### ISSUE THREAD

**Issue by christian-draeger** [skrapeit/skrape.it#166]
**Describe the bug**
Current Fetcher implementation is based on ktor clients apache http client which makes trouble on Android. 

**Expected behavior**
Library should work on Android as it do on server. 

**Additional context**
Switching fetcher implementation to use ktor client over okhttp should lead to first class android support but still supporting server side

Eric provided a hint on the kotlin slack that he could prove swapping the fetcher impl to okhttp will make the android issues go away 
![Screenshot_20211002-210408.jpg](https://user-images.githubusercontent.com/22223458/135729227-9cfa3593-e25e-4af7-9d69-200b6240f545.jpg)

We need to swap implementations of http fetcher and async fetcher to use okhttp

**Comment by eric-labelle** [comment]
I was really busy the last few weeks. I'll try to open a draft PR for your review as soon as I get back to it.

**Comment by christian-draeger** [comment]
Big thanks in advance @eric-labelle

**Comment by dshetyo** [comment]
Any updates on this?Is this lib working fine on andoid?
