### ISSUE TITLE
DOM mode cannot be set

### ISSUE THREAD

**Issue by pvegh** [skrapeit/skrape.it#179]
This page describes how to request the page as DOM to be able to parse a JS rendered page
https://docs.skrape.it/docs/dsl/extract-client-side-rendered-data

The example code doesn't work, mode cannot be set. Maybe the docs are outdated.

**Comment by christian-draeger** [comment]
Hey thx for pointing this out. The example code on the docs page is unfortunately outdated.

All documentation in the github projects readme is up-to-date though. I will try to update the docs page as soon as possible.

please have a look here until docs page is updated: https://github.com/skrapeit/skrape.it#scrape-a-client-side-rendered-page

**Comment by pvegh** [comment]
Thanks, looks like BrowserFetcher is all that's needed currently.
I already tried it, it doesn't contain all the content that is generated by javascript at runtime on the page I need to parse.
