### ISSUE TITLE
[QUESTION] Scrape elements from text\templates block

### ISSUE THREAD

**Issue by QAutomatron** [skrapeit/skrape.it#181]
Hey. Want to scrape some WordPress-based sites with dynamic content using `BrowserFetcher`.
Elements that I want are located in ` <script type="text/template">` block, but the fetcher is not rendered them correctly and mark as `CDATA`
Is there a way to render them? Or maybe I missed something in configuration.

Example 
```
<ul class="products products-container skeleton-loading list pcols-lg-3 pcols-md-3 pcols-xs-2 pcols-ls-2 pwidth-lg-3 pwidth-md-3 pwidth-xs-2 pwidth-ls-1"> 
    <script type="text/template">
//<![CDATA[
"\t\t\n<li class=\"product-col product type-product post-19102 status-publish first instock product_cat-green-stuff-world product_cat-terrain product_tag-green-stuff-world has-post-thumbnail taxable shipping-taxable purchasable product-type-simple\">\n<div class=\"product-inner\">\n\t\n\t<div class=\"product-image\">\n\n\t\t...
//]]>
               </script> 
   </ul> 
```

**Comment by QAutomatron** [comment]
Thanks for such quick response. Provided example is what `BrowserFetcher` returns. 

In real browser it looks like this:
<img width="1314" alt="Screenshot 2022-02-12 at 01 32 07" src="https://user-images.githubusercontent.com/15247795/153684472-553de318-2264-4ef2-8c53-bd525928798b.png">

And in a page source it looks like this (or if i use `HttpFetcher`):
```
                                <div class="archive-products">
                                    <ul class="products products-container skeleton-loading list pcols-lg-3 pcols-md-3 pcols-xs-2 pcols-ls-2 pwidth-lg-3 pwidth-md-3 pwidth-xs-2 pwidth-ls-1">
                                        <script type="text/template">
                                        "\t\t\n<li class=\"product-col product type-product post-19102 status-publish first instock product_cat-green-stuff-world product_cat-terrain product_tag-green-stuff-world has-post-thumbnail taxable shipping-taxable purchasable product-type-simple\">\n ...
</ul></div>
```

But as a workaround i will try to get CDATA block and parse it.

**Comment by christian-draeger** [comment]
FYI:
i created an upstream issue/question at [html-unit project](https://github.com/HtmlUnit/htmlunit/issues/443) which skrape{it} is using internally to render pages. 
i breaked it down to the reason we are getting this CDATA blocks

**Comment by christian-draeger** [comment]
Yeah, I recognized this as well. the text inside the script block is not valid html and includes line indentations (tabs \\t and new lines \\n) . Who knows what WordPress is doing there 😄

But glad to here the work-around was possible
