### ISSUE TITLE
[BUG] KDoc should use Kotlin formatting, not Javadoc

### ISSUE THREAD

**Issue by aSemy** [skrapeit/skrape.it#195]
**Describe the bug**

In some KDoc `{@code ...}` is used

https://github.com/skrapeit/skrape.it/blob/e429fdc1e15763d5dafc887ee4d5c3bd1e1cadd9/html-parser/src/main/kotlin/it/skrape/selects/DocElement.kt#L23

KDoc uses a flavour of Markdown, so replace this with backticks

```kotlin
     /** 
     * For example, given HTML `<p>Hello <b>there</b> now!</p>`, `p.ownText()` returns `"Hello now!",
     */ 
```

**Comment by msotho** [comment]
Hello. I would like to contribute and work on this first bug. Thank you

**Comment by christian-draeger** [comment]
Hello, merge requests are very welcome :)

**Comment by msotho** [comment]
Apologies if already documented somewhere, but is there a standard naming of branches for bugs or features?

**Comment by msotho** [comment]
I believe we can now close this issue?

Thanks.

**Comment by christian-draeger** [comment]
Ah yes, thx for the reminder 😀 and thx again for your help 🙂
