### ISSUE TITLE
How to set jsExecution = true for BrowserFetcher

### ISSUE THREAD

**Issue by sampatsharma143** [skrapeit/skrape.it#235]
I am using scrapeit in a android app , and i want to scrape a CSR website , but after using the BrowserFetcher i am not able to get the html content it's just javascript urls , after checking the code i find out that i will have to set the jsExecution = true but i am not able to do that . 
please share an example of this

**Comment by christian-draeger** [comment]
should work as described here: https://github.com/skrapeit/skrape.it#scrape-a-client-side-rendered-page
using version 1.3.0-alpha.1
