### ISSUE TITLE
[FEATURE]  Add nullable expressions

### ISSUE THREAD

**Issue by xVemu** [skrapeit/skrape.it#236]
**Is your feature request related to a problem? Please describe.**
Kotlin has nullable types, so it's weird that `findFirst` function throws `ElementNotFoundException` instead of returning null. The same applies to `findAll`, why it can't return empty list if none element was found?

**Describe the solution you'd like**
Add some function like `findFirstOrNull` and make `findAll` return empty list, when no elements were found.

**Describe alternatives you've considered**
Currently, I'm using this as a workaround:
```kotlin
    private fun DocElement.findFirstOrNull(selector: String): DocElement? = try {
        findFirst(selector)
    } catch (e: ElementNotFoundException) {
        null
    }
```

**Comment by christian-draeger** [comment]
Please check relaxed parsind option as described here under point 4: https://docs.skrape.it/docs/dsl/extracting-data-from-websites

**Comment by xVemu** [comment]
Still throws error in this scenario:
```kotlin
fun main() = runBlocking {
    getLesson()
}

suspend fun getLesson() = withContext(Dispatchers.IO) {
    skrape(AsyncFetcher) {
        request {
            url = "https://google.com"
        }
        response {
            htmlDocument {
                relaxed = true
                findFirst("body") {
                    children.drop(1).forEach { row ->
                        print(row.findAll("xdddddd"))
                    }
                }
            }
        }
    }
}
```

**Comment by christian-draeger** [comment]
ok i see, this is related to the following issue:

https://github.com/skrapeit/skrape.it/issues/223
https://github.com/skrapeit/skrape.it/pull/227

will be closed as duplicate
