### ISSUE TITLE
[FEATURE] make it possible to add specific properties to an element selection using the DSL

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#4]
instead of picking elements that require a complex css query via query string like so:
`element("div.myClass[myAttr=bar]")` it should be possible to describe the selector using the DSL.

e.g.:

```
element("div") {
    class="myClass"
    attribute="myAttr" to "bar"
}
```
or
```
div {
    class="myClass"
    attribute="myAttr" to "bar"
}
```

old logic still has to be supported.

**Comment by skrapeit** [comment]
already prepared something to calculate valid css selectors as string in https://github.com/skrapeit/skrape.it/blob/master/src/main/kotlin/it/skrape/selects/DynamicSelectorBuilder.kt

and added a [`ScrapebleElements.kt`] (https://github.com/skrapeit/skrape.it/blob/master/src/main/kotlin/it/skrape/core/ScrapebleElements.kt) that allows to set all necessary fields and is extending jsoups `Elements`-class.

**Comment by christian-draeger** [comment]
I already added a [ScrapebleElements.kt] (https://github.com/skrapeit/skrape.it/blob/master/src/main/kotlin/it/skrape/core/ScrapebleElements.kt) that allows to set all necessary fields and is extending jsoups Elements-class.
And furthermore  prepared something to convert `ScrapebleElements` object to a valid css selector string in https://github.com/skrapeit/skrape.it/blob/master/src/main/kotlin/it/skrape/selects/DynamicSelectorBuilder.kt

**Comment by christian-draeger** [comment]
done
