### ISSUE TITLE
[QUESTION] support kotlin.js

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#61]
is someone into building Kotlin multiplattform libraries and could give some advise on what to do / pitfalls to be aware of or would be open to help to make this project a multiplattform lib?

**Comment by Barddo** [comment]
I want to help. I've never made a multiplatform lib in kotlin but I can handle that.

**Comment by skrapeit** [comment]
great :) really thankful that you want to help on this topic.
i have assigned the issue to you and curiously wait for the pull request :)

**Comment by skrapeit** [comment]
if there is something that blocks the project to become Multiplatform or if you need help just let me know :)

**Comment by Barddo** [comment]
I having a issue in which libraries can replace in JS the ones it currently using in JVM, like jacoco, jsoup and junit. Also how to call npm modules from gradle.

**Comment by christian-draeger** [comment]
while hanging around at kotlin conf a month ago or so i wrote an react.js [hello-world app](https://github.com/christian-draeger/kotlin-react-gradle-example/blob/master/build.gradle.kts#L31) that uses gradle and kotlinjs

don't know if that can help.

jacoco plugin is only there to measure test coverage.
not sure what to do regarding junit or how that works.
i think jsoup functionalities could maybe be replaced by using the Document stuff from the kotlin std-lib ? but not sure about that

https://kotlinlang.org/api/latest/jvm/stdlib/org.w3c.dom/-document/index.html

**Comment by Barddo** [comment]
I though that too, the standard library can supply this need. Not sure yet, but I'll try it.
For a while there will be just the core, fetcher, and DSL. Just for the start, later I'll see what can be replaced by jacoco and so on.

**Comment by Barddo** [comment]
> while hanging around at kotlin conf a month ago or so i wrote an react.js [hello-world app](https://github.com/christian-draeger/kotlin-react-gradle-example/blob/master/build.gradle.kts#L31) that uses gradle and kotlinjs

Thank you! It helps a lot.

**Comment by skrapeit** [comment]
> i think jsoup functionalities could maybe be replaced by using the Document stuff from the kotlin std-lib ? but not sure about that
> https://kotlinlang.org/api/latest/jvm/stdlib/org.w3c.dom/-document/index.html

regarding this topic - here is a good summary about  the `org.w3c.dom.Document` https://stackoverflow.com/a/29071604/10562333

from what is written down there I don't think it can be a proper replacement for jsoup. but not sure if it can be done with some kotlinJS lib or native functionalities.

**Comment by Barddo** [comment]
That's true, it would have be rewritten from the scratch.

**Comment by christian-draeger** [comment]
@Barddo Do you have any findings regarding the JS support? Or maybe found specific pain points to make kotlinjs support possible?

**Comment by Barddo** [comment]
It isn’t possible yet call JS code and classes from Kotlin smoothly, you have to make the object structure from the scratch if you want type safety, however it’s possible to add dynamic type, but the IDE and compiler won’t warn you about syntax or logic error, so you have to write a interface in Kotlin with every field and function, and its returning. These both are the two main ways to approach it I found, which I suppose wouldn’t both be elegant solutions. What do you think?
