### ISSUE TITLE
[IMPROVEMENT] publish snapshots to jitpack 

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#63]
We want to publish all commits to the master that have passed the CI build to [jitpack](https://jitpack.io).
Thereby we are able to early test integration of potential release candidates and providing bleeding edge features to users.

Regular / stable releases will still go to mavens central repository

**Comment by christian-draeger** [comment]
done

**Comment by cvb941** [comment]
@christian-draeger JitPack builds seem to be broken now.. https://jitpack.io/com/github/skrapeit/skrape.it/master-be56c07aad-1/build.log

**Comment by christian-draeger** [comment]
hey :)
it's fixed now.
jitpack relies on the gradle install task which is added by the maven publish plugin but the plugin wasn't applied and jitpack just errored when trying to create the jar due executing `gradle install`.

again thx a lot for your hints, this is extremely helpful :)

we are close to finish last tasks for [milestone 1.0.0 ](https://github.com/skrapeit/skrape.it/milestone/1) 
so final release of 1.0.0 is coming close 💯
