### ISSUE TITLE
[FEATURE] add support for DOM tree relevant assertions made with assertK

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#7]
skrape{it} should support well-known assertion libraries by adding custom matchers that are relevant when expecting things in the DOM tree. 
[AssertK](https://github.com/willowtreeapps/assertk) is an well-known and nicely extendable assertion library we want to support.

Please add the following custom matchers that can be used on `Element` objects
* isPresent
* isNotPresent
* isPresentTimes(n)
* hasText("")
* hasTextContainig("")
* hasTextStartingWith("")
* hasTextEndingWith("")
* hasClass("")
* hasClassContainig("")
* hasClassStartingWith("")
* hasClassEndingWith("")
* hasAttribute("" to "")
* hasId("")
* hasIdContainig("")
* hasIdStartingWith("")
* hasIdEndingWith("")
* isDisabled
    * check if element has attribute `disabled`
* hasSrc("")
* hasSrcContaining("")
* hasSrcStartingWith("")
* hasSrcEndingWith("")
* hasTitle("")
* hasTitleContainig("")
* hasTitleStartingWith("")
* hasTitleEndingWith("")
* hasHref("")
* hasHrefContainig("")
* hasHrefStartingWith("")
* hasHrefEndingWith("")

**Comment by christian-draeger** [comment]
decided to not do it
