### ISSUE TITLE
[IMPROVEMENT] automate release process

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#71]
Releasing a new version should happen completely automated.

It should happen on pushing a particular tags to the master (since GitHub Actions doesn't support a parametrized manual build trigger). 

following tags are allowed values and will trigger a corresponding release (bump and commit project version afterwards publish to maven central):

* major (will bump the major version - e.g. 2.11.1 --> 3.0.0 || 2.11.1-alpha1 --> 3.0.0)
* feature (will bump the minor version - e.g. 2.11.1 --> 2.12.0 || 2.11.1-alpha1 --> 2.12.0)
* bug (will bump the patch version - e.g. 2.11.1 --> 2.11.2 || 2.11.1-alpha1 --> 2.11.2)
* alpha (will bump the alpha version - e.g. 2.11.1 --> 2.11.1-alpha1 || 2.11.1-alpha1 --> 2.11.1-alpha2)
* beta (will bump the beta version - e.g. 2.11.1 --> 2.11.1-beta1 || 2.11.1-beta1 --> 2.11.1-beta2)
* rc (will bump the rc version - e.g. 2.11.1 --> 2.11.1-rc1 || 2.11.1-rc1 --> 2.11.1-rc2)

**Comment by christian-draeger** [comment]
added [new github actions workflow](https://github.com/skrapeit/skrape.it/blob/master/.github/workflows/release.yml) that:
* will be triggered on pushed tag
* generate new version depending on tag value

TODO:
* read current version from [gradle.properties](https://github.com/skrapeit/skrape.it/blob/master/gradle.properties#L2)
* bump project version to new version (`VERSION_NAME` in [gradle.properties](https://github.com/skrapeit/skrape.it/blob/master/gradle.properties)`) and push to master
* trigger maven central publish task (`./gradlew publish`)

**Comment by christian-draeger** [comment]
adjust [github actions workflow](https://github.com/skrapeit/skrape.it/blob/master/.github/workflows/release.yml) that:
* will be triggered on pushed tag
* generate new version depending on tag value
* read current version from [gradle.properties](https://github.com/skrapeit/skrape.it/blob/master/gradle.properties#L2)
* bump project version to new version (`VERSION_NAME` in [gradle.properties](https://github.com/skrapeit/skrape.it/blob/master/gradle.properties)`) and push to master

TODO:

* trigger maven central publish task (`./gradlew publish`)

**Comment by DavidJRobertson** [comment]
This is so not how tags are supposed to work...

**Comment by christian-draeger** [comment]
Agree. Just came up with this idea since github actions doesn't support manual triggers AFAIK.

But I agree that we should remove the tags and until github actions will support manual triggers we should just release "by hand" (using gradle command from local machine)

**Comment by DavidJRobertson** [comment]
My biggest issue here is that the versions are not tagged in git. When you do a release, you should tag it with the version number. And those tags should never ever change.

**Comment by christian-draeger** [comment]
good point. i will do for the next releases

**Comment by christian-draeger** [comment]
automatic release via github actions and workflow dispatch with input has been added. thereby i will close this.
