### ISSUE TITLE
[BUG] How to get all div with the same class

### ISSUE THREAD

**Issue by piotrek-py** [skrapeit/skrape.it#73]
**Describe the bug**
I can not extract nested div using scrape.it

**Code Sample**
```
val someHtml = """
            <html>
                    <head>
                        <link rel="shortcut icon" href="https://some.url/icon">
                        <script src="https://some.url/some-script.js"></script>
                        <meta name="foo" content="bar">
                    </head>
                    <body>
                        <div class="content">
                            <div class="row">data</div>
                        </div>
                    </body>
                </html>
        """.trimIndent()
        htmlDocument(someHtml) {
            div {
                withClass = "row"
                findAll {
                    print(this)
                }
            }
        }
```

`Out: []`

**Expected behavior**
`Out: [<div class="row">data</div>]`

**Additional context**
`implementation "it.skrape:skrapeit-core:1.0.0-alpha4.1"`

**Comment by christian-draeger** [comment]
hey,
if you want to get all the texts of `div.row` as list of String you could call `eachText` instead of  `print(this)`.

getting a list of Elements does not seem to work for some reason. as you mentioned, `this` is an empty array in that case 🤔
if i find the time i will have a look into it within the next days

**Comment by christian-draeger** [comment]
Hey
Version 1.0.0-alpha5 has been released. This issue should be fixed now
