### ISSUE TITLE
Ssl certificate checking skip

### ISSUE THREAD

**Issue by ghost1372** [skrapeit/skrape.it#75]
Hello i'm using the jsoup library to parse html, The website I want to parse cant verify SSL so jsoup Could not receive information. That's why I have to disable SSL checker, now i want to know that Can this library disable SSL checker like jsoup?

**Comment by christian-draeger** [comment]
Hey,
We released version 1.0.0-alpha6 which includes a new request option that will trust all certificates. It can be used as follows:

```
skrape {
url = "..." 
sslRelaxed = true
... 
} 
```

**Comment by cvb941** [comment]
@christian-draeger The sslRelaxed variable is defined as a read-only val.
```kotlin
data class Request(
...
 val sslRelaxed: Boolean = false
)
```
I believe it should be a _var_, am I correct?

**Comment by christian-draeger** [comment]
@cvb941 thx for pointing this out, it is fixed now :)
