### ISSUE TITLE
[FEATURE] add support for DOM tree relevant assertions made with assertJ

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#8]
skrape{it} should support well-known assertion libraries by adding custom matchers that are relevant when expecting things in the DOM tree.
[AssertJ](https://joel-costigliola.github.io/assertj/) is an well-known and nicely extendable assertion library we want to support.

Please add the following custom matchers that can be used on Element objects

isPresent
isNotPresent
isPresentTimes(n)
hasText("")
hasTextContainig("")
hasTextStartingWith("")
hasTextEndingWith("")
hasClass("")
hasClassContainig("")
hasClassStartingWith("")
hasClassEndingWith("")
hasAttribute("" to "")
hasId("")
hasIdContainig("")
hasIdStartingWith("")
hasIdEndingWith("")
isDisabled
check if element has attribute disabled
hasSrc("")
hasSrcContaining("")
hasSrcStartingWith("")
hasSrcEndingWith("")
hasTitle("")
hasTitleContainig("")
hasTitleStartingWith("")
hasTitleEndingWith("")
hasHref("")
hasHrefContainig("")
hasHrefStartingWith("")
hasHrefEndingWith("")

**Comment by derlin** [comment]
Is it normal most of those matchers are also listed in https://github.com/skrapeit/skrape.it/issues/7 ? Do we agree what you want is to implement those, not use the underlying assertj or assertk mechanism ? Thus, there is definitely an overlap (matchers would have to be implemented only once in either this or the other issue).

**Comment by christian-draeger** [comment]
Good point. The idea is to have extension for either assert and assertk. But since assertk is assert under the hood I guess you are right and assertj support/custom matchers would also work for assertk (maybe, just a guess didn't had a deeper look so far).
From that point of view it would make sense to start with assertj support
