### ISSUE TITLE
[BUG] Skrape.it dependencies missing when trying to build for tests

### ISSUE THREAD

**Issue by joelshea** [skrapeit/skrape.it#81]
**Describe the bug**
Hello!  I am trying to use Skrape for unit testing a website we are building, but I’m running into a lot of trouble immediately.  I have including the dependencies like this:

```
testImplementation("it.skrape:skrapeit-core:1.0.0-alpha6")
testImplementation("it.skrape:skrapeit-ktor:1.0.0")
```

But if I try to use the Ktor extension, I get the following error:

>Cannot access class ‘org.jsoup.nodes.Document’. Check your module classpath for missing or conflicting dependencies

If I just try to use the Skrape core directly, I get this:

>Unresolved reference: strikt

Everything looks fine in the IDE and it resolves things automatically, but unfortunately I cannot build.  Have I missed something?

**Comment by christian-draeger** [comment]
Hey thx for reporting. The unresolved reference should be related to #76. I will try to have a look tomorrow.

**Comment by christian-draeger** [comment]
we make the assertions on our own now - no 3rd party library involved anymore and therefore also no dependency clashes or unresolved dependencies anymore
will be part of the 1.0.0 final release 🥳
