### ISSUE TITLE
[FEATURE] Add access to all elements in DocElement

### ISSUE THREAD

**Issue by sanatik** [skrapeit/skrape.it#83]
**Is your feature request related to a problem? Please describe.**
I think it would be really awesome, if users have access to `org.jsoup.nodes.Element#getAllElements()` function from `it.skrape.selects.DocElement` wrapper.
My use case is pretty simple, I have a `div` and would like to iterate over each element inside.

**Describe the solution you'd like**
Any of the following functions would work for me:
- `it.skrape.selects.DocElement#findAll()` without input parameters
- `it.skrape.selects.DocElement#getElement()` returning `org.jsoup.nodes.Element`

**Describe alternatives you've considered**
At the moment I do not see how I could access all children of given `DocElement`

**Comment by skrapeit** [comment]
hey thx for the feature request. this makes totally sense to me.
we should add a `allElements ` member to DocElement that represents all elements under this element including itself as well as a `findAll {}` lambda function.
