### ISSUE TITLE
[IMPROVEMENT] Configure OkHttp client ConnectionPool `keepAlive` value

### ISSUE THREAD

**Issue by suushiemaniac** [skrapeit/skrape.it#85]
Library version: 1.0.0-alpha6
OS: Linux Manjaro 19.0.2
Kernel: Linux 5.5.16

When executing any website scraping using the `extract {}` DSL with default `Mode.SOURCE` the JVM hangs roughly 90 seconds before shutting down.

From my investigation, I am fairly confident this is due to the fact that the underlying `OkHttp` client used by `KoHttp` keeps a pool of threads used for connection handling. These threads are unwilling to die even when the `main` method was fully executed.

Reproduce: Write a main method that scrapes the title from any arbitrary website, print that title to the console. When executed "on my machine" :tm: the process does not terminate until ~90 seconds after the title has been printed.

Solution: Configure the KoHttp client better, or at least allow the user to pass configuration values for the `keepAlive` property of `okhttp3.ConnectionPool`

**Comment by skrapeit** [comment]
hey,
thanks for reporting.
i tried on my Mac book and can not reproduce it (java version: AdoptOpenJDK 11.0.6 2020-01-14). 

![skrape-it-issue85](https://user-images.githubusercontent.com/46688980/79115673-bf7dbe00-7d86-11ea-9f0d-8e99ea75e74f.gif)

i will quickly try on my manjaro installation.

**Comment by suushiemaniac** [comment]
Thanks for the feedback! Indeed, the code _does_ immediately terminate with the example from your GIF, even on my machine...

I played around some more, and the issue seems to be related to the website being scraped! I can reproduce the issue with the exact code from your GIF when using the URL `https://www3.nhk.or.jp/news/easy/k10012383451000/k10012383451000.html`.
Based on this new finding, should I close this issue and report to OkHttp instead?

**Comment by skrapeit** [comment]
yes. sounds like an issue on OkHttp's side.
i will close the issue. thx for investigating
