### ISSUE TITLE
[FEATURE] CssSelector shorthands on nested DocElement entities

### ISSUE THREAD

**Issue by suushiemaniac** [skrapeit/skrape.it#86]
**Is your feature request related to a problem? Please describe.**
I think it would be really awesome if skrape{it} would provide the `it.skrape.selects.html5` selector shorthands for elements as well (instead of only for top-level documents)

**Describe the solution you'd like**
The extension functions should be defined on a common superclass of `Doc` and `DocElement` to allow for nested selectors

**Describe alternatives you've considered**
1. Write one top-level selector that directly accesses the nested properties. Frustrating because:
    - I have to compile the CSS selector string entirely by hand instead of with the beautiful type-safe `CssSelector` DSL
    - doing so does not encourage reusability, for example if you want to scrape several DOM elements within one given `<div>`
2. Use the direct bridge to `jsoup`'s `select` mechanism. Ugly because:
    - No type safety, see above.
    - Uses two different selection mechanisms, makes source code harder to read.

**Additional context**
In the underlying `jsoup` library, you can use `select` on the top-level document as well as any `Element` because the `Document` class simply `extend`s from `Element`.
I'm not sure whether that solution would be appropriate for `skrape{it}` as well, because I'm not initmately familiar with the design decisions for this library. However, only being able to use the DSL on top-level feels like a complete waste of effort since the `CssSelector` hierarchy is very useful and versatile.

**Comment by christian-draeger** [comment]
hey i just started with some selectors. dunno if this can be made more elegant. if you have another idea please let me know.
now it's pssible to use the DSL to select  elements by nesting calls on the doc, css selectors and  elements

**Comment by suushiemaniac** [comment]
Thanks for tackling the issue so promptly! As far as I can tell, your "solution" essentially involves a lot of copy-pasta, which doesn't seem like a clean implementation. I don't have a fully fledged-out plan myself, but here's my initial idea:

1. The current extension methods for type-safe DSL all seem to be "convenient aliases" to the `Doc#selection` method. That method in turn compiles a `CssSelector` by using the internal jsoup `Document`.
2. Create an interface along the lines of `CssSelectable` (find a better name, that's only rough draft here) that looks like this: (`fun selection` is literally copied from `Doc` except the jsoup reference)
```kotlin
interface CssSelectable {
  val jsoupDocument: Document

  fun <T> selection(cssSelector: String, init: CssSelector.() -> T) =
    CssSelector(rawCssSelector = cssSelector, doc = this.jsoupDocument).init()
}
```
3. Have both skrapeit's `Doc` and `DocElement` implement the `CssSelectable` interface from (2), providing their jsoup handle to the extension methods
4. Refactor the extension methods to work like `CssSelectable.div` instead of `Doc.div`

Does that make sense? In any case, you should use some form of "type hierarchy solution" to avoid the redundant code from https://github.com/skrapeit/skrape.it/commit/39da95e0f6909f7994b13f5532074fc9bdb23b0a !!

**Comment by skrapeit** [comment]
this sounds like a great solution for me.
would you mind to send a pull request? this would be really nice.

**Comment by suushiemaniac** [comment]
Working on it right now!
