### ISSUE TITLE
[FEATURE] Allow for custom HttpClient implementations

### ISSUE THREAD

**Issue by suushiemaniac** [skrapeit/skrape.it#87]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to let skrape{it} open an `OkHttp3` client (via `KoHttp`) when I already use ktor clients in the rest of my code for other purposes.

**Describe the solution you'd like**
Provide an interface (similar to the existing `it.skrape.core.fetcher.Fetcher`) that the user has to fulfill in order to use their own Http client implementation

**Describe alternatives you've considered**
Fetching the HTML code manually and loading it into skrape{it} as raw String.
Works, but feels like a dirty workaround.

**Additional context**
When using the web-scraping functionality of skrape{it} in a bigger project, I already use a (custom configured) [ktor client](https://ktor.io/clients/index.html) with a connection pool and other fancy stuff. It feels wrong to fire up OkHttp3 only to fetch two website HTML documents.

There already exists a `Fetcher` interface, and I believe that if you changed the signature from `fun fetch(): Result` to `fun fetch(request: Request): Result` that would already be enough to allow for custom client implementations. Perhaps this will also require de-coupling some configuration-specific values like SSL verification and timeouts into a second `Configuration` interface because most clients will only require that kind of information once upon creation and not upon every single request.

Then, lastly, the user has to be able to "override" the `client` engine with any custom-built adapter in the same `skrape {}` block where things like `url` and `mode` are currently configured. It is unclear how this mechanism will (or won't) supersede the `mode` setting.

**Comment by skrapeit** [comment]
hey, you are absolutely correct and I was already thinking about it in the past. Thereby I totally agree that this would be a great and useful feature. if you have specific ideas or suggestions on an optimal design or implementation you are very welcome to share them. 
Optionally, a pull request would be awesome :)

**Comment by suushiemaniac** [comment]
I have a good idea how to implement this feature using sealed classes.
I anticipate to have enough time for a PR in the second half of this week. Should I self-assign this issue?

**Comment by skrapeit** [comment]
awesome :) big thx in advance

**Comment by christian-draeger** [comment]
i think we could/should just kill the `mode` setting in that case because the only thing the mode setting is doing is switching between OkHttp client and HtmlUnit client. If the user would have the possibility to pass the client implementation they want (either their own or `HttpFetcher` / `BrowserFetcher`). i would like to still ship the `HttpFetcher` and `BrowserFetcher` for people who don't have the need to implement the http client themselfs. I think especially the JS excution support that comes with the `BrowserFetcher` (HtmlUnit) is making skrape{it} unique but maybe it would need to get a more applicable name.

**Comment by christian-draeger** [comment]
What I could also imagine and think would be a nice solution is to pull the clients completely out of the skrape{it} core and just leave an interface that than can be implemented by people or we could just deliver the implementations we already have (okhttp and html-unit) as optional dependencies.
