### ISSUE TITLE
[FEATURE] add support for DOM tree relevant assertions made with Kotlintest

### ISSUE THREAD

**Issue by skrapeit** [skrapeit/skrape.it#9]
skrape{it} should support well-known assertion libraries by adding custom matchers that are relevant when expecting things in the DOM tree.
[KotlinTest](https://github.com/kotlintest/kotlintest) is a well-known testing and assertion library we want to support.

Please add the following custom matchers that can be used on Element objects

- shouldBePresent
- shouldNotBePresent
- shouldBePresentTimes(n)
- shouldHaveText("")
- shouldHaveTextContainig("")
- shouldHaveTextStartingWith("")
- shouldHaveTextEndingWith("")
- shouldHaveClass("")
- shouldHaveClassContainig("")
- shouldHaveClassStartingWith("")
- shouldHaveClassEndingWith("")
- shouldHaveAttribute("" to "")
- shouldHaveId("")
- shouldHaveIdContainig("")
- shouldHaveIdStartingWith("")
- shouldHaveIdEndingWith("")
- shouldBeDisabled
    * check if element has attribute disabled
- shouldHaveSrc("")
- shouldHaveSrcContaining("")
- shouldHaveSrcStartingWith("")
- shouldHaveSrcEndingWith("")
- shouldHaveTitle("")
- shouldHaveTitleContainig("")
- shouldHaveTitleStartingWith("")
- shouldHaveTitleEndingWith("")
- shouldHaveHref("")
- shouldHaveHrefContainig("")
- shouldHaveHrefStartingWith("")
- shouldHaveHrefEndingWith("")

**Comment by faogustavo** [comment]
@skrapeit do you think it's better to add them here or in the KotlinTest lib?

**Comment by skrapeit** [comment]
If the KotlinTest project maintainers will accept to support skrape.it with custom assertions this would be awesome and preferred. If not I guess it's OK if skrape.it will provide the custom matchers itself

**Comment by faogustavo** [comment]
@skrapeit just open an issue there. I already implemented some matchers in the lib, and if they feel comfortable with adding jsoup matchers, I can do this one.

**Comment by faogustavo** [comment]
@christian-draeger whats the meaning of `shouldBePresent`? How do I check it?

**Comment by skrapeit** [comment]
Nice :) thx a lot
`Element.shouldBePresent` assertion should fail if a given element is not present in the Document.

**Comment by faogustavo** [comment]
@skrapeit I'm not too much available as I wanted to continue developing those matchers. So, I'll remove the WIP from the PR. 
As soon as they approve, the main structure will be done to add new matchers as needed.
