### ISSUE TITLE
[BUG] element extraction methods like `$`, el, element and elements not found

### ISSUE THREAD

**Issue by pedramkeyani** [skrapeit/skrape.it#90]
**Describe the bug**
The documentation for [extracting data from a website](https://docs.skrape.it/docs/dsl/extracting-data-from-websites) is out of date and does not compile.

**Code Sample**
`import it.skrape.extract
import it.skrape.selects.`$` <-- is not in the selects package and doesn't compile
import it.skrape.selects.el <-- is not in the selects package and doesn't compile
import it.skrape.skrape

data class MyScrapedData(
    val userName: String, 
    val repositoryNames: List<String>
)

fun main() {
    val githubUserData = skrape {
        url = "https://github.com/skrapeit"
        
        extract {
            MyScrapedData(
                    userName = el(".h-card .p-nickname").text(),
                    repositoryNames = `$`("span.repo").map { it.text() }
            )
        }
    }
    println("${githubUserData.userName}'s repos are ${githubUserData.repositoryNames}")
}`

**Expected behavior**
I've tried all but the most basic examples to learn the different components of scraping. selects.element and selects.elements are also used in the examples but they don't appear to be in the code. This very well could be a problem with how I have or haven't configured intellij.

**Comment by pedramkeyani** [comment]
I also should note that I'm using Intellij and have tried this with it.skrape:skrapeit-core:RELEASE as well as 6 alpha, 4 alpha and 4.1 alpha.

**Comment by christian-draeger** [comment]
Hey,
the methods you described has been available at really early versions of skrape{it}. They are not supported anymore in the versions you described. 
Please let me know it there is someexame in the docs that is still showing the old syntax, so it can be changed. 

New syntax(alpha6) 
https://github.com/skrapeit/skrape.it#parse-html-and-extract-it

**Comment by pedramkeyani** [comment]
Hi Christian, here is the document that has the old style. Also it allws you to select between all the versions of the API except for the newer ones (6 alpha) https://docs.skrape.it/docs/dsl/extracting-data-from-websites

I also found examples in the documentation of using selects.element and selects.elements but I can't find it right now.  I'll look around for it.

**Comment by christian-draeger** [comment]
Ok thanks. I will update the examples soon. Thx for pointing this out. Let me know if the other (newer example in the readme) works for you :)

**Comment by pedramkeyani** [comment]
Thanks for following up. The example in the readme worked (from what I remember yesterday). One of the challenges I am having is how to use the different features to scrape a little more elegently. I stumbled around the code and figured out how to use withClass and then rawCssSelector which was more powerful but I'm still not able to figure out how to iterate through dom elements (for all the elements of a list and map their hrefs to the text). One example of something I need to do is visit dom elements and grab multiple pieces of information to put into an object and store that for later. It may be easier to go through the details on slack so I messages you on the kotlinlang channel.  

`htmlDocument {

/*
                    li {
                        rawCssSelector = "div.jokes-nav > ul > li"

                         links.addAll(findAll { eachText() })
                    }
*/

                    a {
                        rawCssSelector  = " div.jokes-nav > ul > li > a"

                        findAll {
                            println(eachHref())
                            println(eachText())

                        }
                    }
                }`

**Comment by christian-draeger** [comment]
Ok cool, I will close this one for now

**Comment by skrapeit** [comment]
related to #91
