### ISSUE TITLE
[FEATURE] Access cookies in Result

### ISSUE THREAD

**Issue by andb3** [skrapeit/skrape.it#97]
**Is your feature request related to a problem? Please describe.**
I'm having trouble getting the response cookies for requests I'm trying to make.

**Describe alternatives you've considered**
You can currently access cookies through getting the "Set-Cookie" header but if there are multiple "Set-Cookie" headers (which occurs if there multiple cookies returned in the response) then only one of those headers will be accessible, and the others are lost.

**Describe the solution you'd like**
I think that adding a `cookies` field to the `Result` class that is a list of cookies from the response would be the best non-breaking change. The headers field could be changed from a Map to a List to alleviate the above problem but that would break existing code, and would be less convenient than having a dedicated field. Thanks!

**Comment by christian-draeger** [comment]
Will have a look within the next days

**Comment by christian-draeger** [comment]
thx @andb3 :)
I really want to give props to every contribution. Do you want your name to pop-up over here? https://docs.skrape.it/docs/about-skrape-it :)

**Comment by andb3** [comment]
Yeah, that'd be great, thanks!
